### ISSUE TITLE
Depends on puppet-extlib

### ISSUE THREAD

**Issue by kwisatz** [dhoppe/puppet-apticron#3]
Hi, despite what it says in the README, looks like this module also requires a module implementing _default_content()_. On puppet forge, you list **mod 'puppet-extlib', '1.0.0'** as a dependency but that module won't install on our server (Puppet 3.8):

```
root@puppet:~# puppet module --modulepath '/etc/puppet/environments/production/modules' install --ignore-dependencies puppet/extlib
Notice: Preparing to install into /etc/puppet/environments/cl1_prod/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not install module 'puppet-extlib' (???)
  No version of 'puppet-extlib' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
```

However, what works is example42/stdmod which also implements that function.

**Comment by dhoppe** [comment]
@kwisatz You are absolutely right. I fixed the version of the module `puppet/extlib` and added an entry to the `README.md`.

**Comment by kwisatz** [comment]
Thank you!
